- Snowplow/SnowplowPayload.m
- SnowplowTests/TestPayload.m
There's no support for URL Safe or non-padding Base64 in the iOS SDK, so post-process the result to fix it. Closes #149
> Use URL-safe Base64 without padding

- Snowplow.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Add IDEWorkspaceChecks.plist to repo, so checks Xcode has run are shared with other developers 
Addresses issue #354
> Commit IDEWorkspaceChecks.plist to repo

- Snowplow iOSTests/TestUtils.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/SPUtilities.h
- Snowplow/SPUtilities.m
The version 1.1.4 update the code about the Apple IDFA.
The #447 add AdSupport module in the framework causing issues during the submission of apps to the App Store.
The current implementation let superfluous AdSupport framework because the class loading of `ASIdentifierManager` is done at runtime and not checked at compile time.
> Fix IDFA rejection when app submitted with v.1.1.4

- Snowplow iOSTests/TestTracker.m
- Snowplow iOSTests/TestUtils.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/SPDevicePlatform.h
- Snowplow/SPDevicePlatform.m
- Snowplow/SPSubject.m
- Snowplow/SPTracker.h
- Snowplow/SPTracker.m
- Snowplow/SPUtilities.h
- Snowplow/SPUtilities.m
- Snowplow/ios.modulemap
- SnowplowTracker.podspec
Adapted the code to the same behaviour of the Android tracker where the platform parameter `p` can be overwritten by the developer.
By default iOS app sets automatically the parameter 'p' (platform) as `mob` and desktop app sets it to `pc`. However, there are cases where you want to specify that differently by the default option.
On the tracker setup you can override the device platform entry calling:
```
[tracker setDevicePlatform: SPDevicePlatformGameConsole];
```
It resets the parameter `p` (platform) to the new value.
[Here](https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#1-common-parameters-platform-and-event-independent) a full list of the supported platform values.
> Allow overwriting of the 'platform' parameter (close #476)

- Snowplow/SPPayload.m
The param type for `dict` is `NSDictionary` but the caller can pass in an immutable variety, like here:
https://github.com/snowplow/snowplow-objc-tracker/blob/4c28d7e8a3690cd5fd708b97e56db6dc14a7ee1f/Snowplow/SPTracker.m#L501-L502
Stop crashes like below that can occur via mutations of the passed in dictionary by ensuring we are enumerating over an immutable dictionary.
**Crash report on non-main thread:**
```
NSGenericException
SPPayload.m:59
*** Collection <__NSDictionaryM: 0x280c4db80> was mutated while being enumerated.
Sep 28th, 2019, 15:33:39 UTC
STACKTRACE
CrashReporter Key:  3d130da70c9c56af1526e9e41b6b0a11d319ce86
Hardware Model:     iPhone9,3
Process:            REDACTED
Identifier:         REDACTED
Version:            REDACTED
OS Version:         iOS 13.1.1
NSGenericException: …
```
> Ensure addDictionaryToPayload enumeration over immutable dictionary (close #480)

- Snowplow iOSTests/TestUtils.m
- Snowplow/SPEvent.h
- Snowplow/SPEvent.m
- Snowplow/SPScreenState.h
- Snowplow/SPScreenState.m
- Snowplow/SPSession.m
- Snowplow/SPTracker.m
- Snowplow/SPUtilities.h
- Snowplow/SPUtilities.m
Fix #483 
As reported in the linked issue, the screen context wasn't correctly updated when the app send a screenView event. It used to work correctly only with automatic screenView tracking.
The bug is related to the software design so I needed to refactor a bit the logic behind ScreenState updating.
> Fix screen context not correctly updated on screenView events (close #483)

- Examples/SnowplowSwiftSPMDemo/SnowplowSwiftSPMDemo.xcodeproj/project.pbxproj
- Examples/SnowplowSwiftSPMDemo/SnowplowSwiftSPMDemo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Examples/SnowplowSwiftSPMDemo/SnowplowSwiftSPMDemo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Examples/SnowplowSwiftSPMDemo/SnowplowSwiftSPMDemo/Info.plist
- Package.swift
- Snowplow/SPEventStore.m
- Snowplow/UIViewController+SPScreenView_SWIZZLE.h
Adding support for Swift Package Manager would allow your users to stop using CocoaPods or Carthage and move a solution already integrated on Xcode.
Unfortunately 2 of your headers had to be modified in order for the package to build using SPM.
I understand these changes will break things, but my knowledge handling header files is not that good, maybe somebody in your team knows how to avoid changing:
`#import <fmdb/FMDB.h>`
to
`#import <FMDB.h>`
I was able to add successfully this package as a dependency on a project using Swift 5.2
I'm sorry for spamming your CI, there is no other way to test if the configuration on the Package Manifest is going to work and if the changes I made on your headers are affecting other deployment options.
> Add support for Swift Package Manager

- Examples/CommonSwiftCode/InterfaceController.swift
- Examples/CommonSwiftCode/PageViewController.swift
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Headers/Private/SnowplowTracker/SPGdprContext.h
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Pods.xcodeproj/project.pbxproj
- Snowplow iOSTests/TestGeneratedJsons.m
- Snowplow iOSTests/TestScreenState.m
- Snowplow macOSTests/Snowplow_macOSTests.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/SPGdprContext.h
- Snowplow/SPGdprContext.m
- Snowplow/SPTracker.h
- Snowplow/SPTracker.m
- Snowplow/Snowplow.h
- Snowplow/Snowplow.m
- Snowplow/UIViewController+SPScreenView_SWIZZLE.m
Implementation of GDPR context.
Please review this suggested documentation:
----
The GDPR context attaches a context with the GDPR basis for processing and the details of a related document (eg. a consent document) to all events which are fired after it is set.
It takes the following arguments:
|      **Name** | **Description**             | **Required?** | **Type** |
|--------------:|:----------------------------|:--------------|:---------|
|       `basis` | GDPR Basis for processing | Yes           | Enum String   |
|     `documentId` | ID of a GDPR basis document     | No           | String   |
|        `documentVersion` | Version of the document        | No            | String   |
| `documentDescription` | Description of the document | No            | String   |
The required …
> Add GDPR context (close #425)

- Snowplow iOSTests/TestUtils.m
- Snowplow/SPUtilities.m
- Snowplow/UIViewController+SPScreenView_SWIZZLE.m
There are few methods deprecated in the last iOS versions:
- Fix deprecated keyWindow (#492)
- Fix deprecated CFURLCreateStringByAddingPercentEscapes (#493)
- Replace deprecated CTTelephonyNetworkInfo methods (#479)
> Replace deprecated methods

- Snowplow/SPEvent.h
- SnowplowTracker.podspec
Fixes a regression in v1.3.0 by adding missing references to the public `SPConsentDocument.h` header.
> Add missing references to SPConsentDocument.h (closes #507)

- Snowplow/SPSession.h
- Snowplow/SPSession.m
- Snowplow/SPTracker.h
- Snowplow/SPTracker.m
Adds public access to an `SPTracker`'s current session id. Closes #508
> Current session id access (closes #508)

- Package.swift
When support for Swift Package Manager was added to the snowplow-objc-tracker, its FMDB dependency was updated with SPM support, but not yet properly tagged with a new version. I believe that's why the dependency was added pointing to a specific commit. 
This was giving me the following error when I added the snowplow tracker through SPM, pointing to version 1.3.0: `package snowplow-objc-tracker is required using a version-based requirement and it depends on unversion package fmdb`. The workaround for this is to either add the snowplow tracker pointing to a specific commit as well, or use master (which could result in uncontrolled updates with breaking changes)
Since then the FMDB update with support for SPM has been tagged as version 2.7.6. This means that, once we add that version to …
> Specifcy FMDB version instead of commit in Package.swift

- Snowplow iOSTests/TestEvent.m
- Snowplow iOSTests/TestTracker.m
- Snowplow/SPEcommerce.m
- Snowplow/SPEventBase.h
- Snowplow/SPEventBase.m
- Snowplow/SPTracker.m
- Snowplow/SPTrackerEvent.m
The event ID is set in the event constructor. We want the event ID set when the event is tracked. Unless the user has set it programmatically.
> Renew event ID when event object is reused (close #521)

- Snowplow/SPScreenView.m
TransitionType field on ScreenView is not correctly reported in the payload.
> ScreenView event doesn't track transitionType (close #516)

- Snowplow iOSTests/TestEvent.m
- Snowplow/SPEventBase.h
- Snowplow/SPEventBase.m
- Snowplow/SPTracker.m
- Snowplow/SPTrackerEvent.h
- Snowplow/SPTrackerEvent.m
@paulboocock This should be a comment fix of the trueTimestamp methods, but meanwhile I noticed that some type conversions and math operations can cause minor precision loss in the decimals, so I think it's worth to be a patch for the just released trueTimestamp feature.
> TrueTimestamp has to be set in seconds (close #532)

- Examples/CommonSwiftCode/PageViewController.swift
- Examples/SnowplowSwiftCocoapodsDemo/Podfile.lock
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Headers/Private/SnowplowTracker/SPDiagnosticLogger.h
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Headers/Private/SnowplowTracker/SPLogger.h
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Headers/Private/SnowplowTracker/SPTrackerError.h
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Local Podspecs/SnowplowTracker.podspec.json
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Manifest.lock
- Examples/SnowplowSwiftCocoapodsDemo/Pods/Pods.xcodeproj/project.pbxproj
- Snowplow/SPLogger.h
- Snowplow/SPLogger.m
- Snowplow/SPTracker.h
- Snowplow/SPTracker.m
Allow the app to receive logs (Error, Debug, Verbose) from the tracker.
Suggested documentation:
---
The tracker is tested with different platforms and versions but there are rare situations where an error can be generated. The tracker will manage these errors to avoid crashes of the app and assure that the events are not lost.
However, it can be useful to observe logs and errors from the tracker in order to narrow down a possible issue. Perhaps due to a mistake in the instrumentation of the tracker in the app or other unexpected behaviour.
We allow the developer to have a full visibility of the tracker logs. _Please, take care to avoid sharing of sensitive information through the logs when in production environment_.
At tracker configuration you can decide which log level you want to …
> Report logs to the app (close #534)

- .gitignore
- Package.resolved
- Package.swift
Since Xcode 12 is released and the minimum deployment target handling was updated for the Swift Package Manager, the current situation with `snowplow-objc-tracker` and its dependency `FMDB` does not meet the requirements anymore.
Because the minimum deployment target of `FMDB` is `v9` and the one from `snowplow-objc-tracker` is `v8`, Xcode complains that `v8` is too small. In other words, a dependency needs to fulfil the minimum deployment target version of the host (snowplow).
> Enable Xcode 12 support for Swift Package Manager

- Snowplow/SNOWReachability.m
`CFRelease` was only called in the `reachabilityForInternetConnection` method, in case the object failed to be allocated.
In case the object was created, the reachability ref was never released, causing a memory leak.
Reproducible by running Leaks Instrument and tracking an event. SP related stack trace from instruments:
```
0 libsystem_malloc.dylib _malloc_zone_malloc
1 CoreFoundation _CFRuntimeCreateInstance
2 SystemConfiguration __SCNetworkReachabilityCreatePrivate
3 SystemConfiguration SCNetworkReachabilityCreateWithAddress
4 MyApp +[SNOWReachability reachabilityForInternetConnection]
5 MyApp +[SPUtilities getNetworkType]
6 MyApp -[SPSubject setMobileDict]
7 MyApp -[SPSubject initWithPlatformContext:andGeoContext:]
```
This PR adds a `CFRelease` in the `dealloc` method. Instruments no …
> Fix leak on SNOWReachability

- Snowplow iOSTests/TestSession.m
- Snowplow/Internal/Session/SPSession.h
- Snowplow/Internal/Session/SPSession.m
Multiple tracker instances needs to have independent session info.
The tracker 1.x used to store some information about the session in the filesystem.
That would cause interferences between trackers in a multi-tracker app.
> Store sessions info separately per tracker namespace (close #570)

- Snowplow iOSTests/TestSession.m
- Snowplow/Internal/Configurations/SPTrackerConfiguration.m
- Snowplow/Internal/Session/SPSession.m
As planned, I set lifecycle optional.
In order to keep the behaviour similar between Android and iOS, I've also disabled the background/foreground index in case the lifecycle tracking is disabled. In that case all the events will be considered in foreground.
> Set lifecycle tracking off by default (close #587)

- Snowplow/UIViewController+SPScreenView_SWIZZLE.h
- Snowplow/UIViewController+SPScreenView_SWIZZLE.m
When I try integrate library to macOS target via SPM I get error, because UIKit does not exists.
I just add precompile checks, because spm does not allow add exceptions for file.
> Fix macOS target for SPM (close #593)

- Snowplow/Internal/Utils/SPUtilities.h
- Snowplow/Internal/Utils/SPUtilities.m
Closes issue #589 
Replaces a custom macro condition with standard availability macros. Fixes compatibility with the Swift Package Manager on [Xcode 12.5](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes)
**Before:**
**After:**
> Fix missing method decorations when using Swift Package Manager on Xcode 12.5

- Snowplow/Internal/Tracker/SPServiceProvider.m
Build on CaseSensitive file systems failed because can't find header file.
> Fix for CaseSensitive file systems (close #622)

- Snowplow/Internal/SPTrackerConstants.h
- Snowplow/Internal/SPTrackerConstants.m
- Snowplow/Internal/Session/SPSession.m
As explained in the issue, we need to keep a unique session userID for all the tracker instances of the same app.
The session userID will be part of the collection of IDs explained in the RFC for the tracker v2: https://discourse.snowplowanalytics.com/t/rfc-mobile-trackers-v2-0/4370
"Installation ID: created by the tracker at first execution (it’s the session_userId that can be tracked even if the session context is turned off). The installation ID will be constant until the app deletion."
> Fix Session UserID not consistent among tracker instances (close #630)

- Snowplow iOSTests/TestDataPersistence.m
- Snowplow iOSTests/TestMemoryEventStore.m
- Snowplow iOSTests/TestSQLiteEventStore.m
- Snowplow iOSTests/TestSession.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/Emitter/SPEmitter.m
- Snowplow/Internal/RemoteConfiguration/SPConfigurationCache.m
- Snowplow/Internal/SPTrackerConstants.h
- Snowplow/Internal/SPTrackerConstants.m
- Snowplow/Internal/Session/SPSession.h
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Storage/SPMemoryEventStore.h
- Snowplow/Internal/Storage/SPMemoryEventStore.m
- Snowplow/Internal/Utils/SPDataPersistence.h
- Snowplow/Internal/Utils/SPDataPersistence.m
- Snowplow/Snowplow-umbrella-header.h
- Snowplow/include/SPMemoryEventStore.h
The crash on tvOS (and also watchOS could be affected) is caused by accessing the filesystem.
The data stored on filesystem has been moved on UserDefaults or in memory:
- EventStore: from SQLite to in-memory
- Session: from filesystem to NSUserDefaults
- Remote Config: from filesystem to in-memory
> Fix crash on tvOS caused by access to filesystem (close #621)

- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/Entities/SPLifecycleEntity.h
- Snowplow/Internal/Entities/SPLifecycleEntity.m
- Snowplow/Internal/Events/SPBackground.h
- Snowplow/Internal/Events/SPForeground.h
- Snowplow/Internal/Tracker/SPLifecycleState.h
- Snowplow/Internal/Tracker/SPLifecycleState.m
- Snowplow/Internal/Tracker/SPLifecycleStateMachine.h
- Snowplow/Internal/Tracker/SPLifecycleStateMachine.m
- Snowplow/Internal/Tracker/SPTracker.m
- Snowplow/include/SPLifecycleEntity.h
As explained in the issue, we want to track the app state as a context in all the events.
This should help the data modelling phase.
It's enabled by default and it doesn't require any particular configuration.
**Update the documentation: TrackerConfiguration new settings**
> Add lifecycle context to indicate app state when the event is tracked (close #637)

- Snowplow/Internal/Session/SPSession.m
This may clash with the refactor in #638 but putting it here for visibility for @AlexBenny 
Allows lifecycle tracking on iOS and tvOS.
> Support lifecycle reporting for tvOS (close #640)

- Snowplow iOSTests/TestDataPersistence.m
- Snowplow/Internal/Utils/SPDataPersistence.h
- Snowplow/Internal/Utils/SPDataPersistence.m
The user reports some crashes starting from SPDataPersistence for some devices. Unfortunately, the crash is not fixable restarting the app or restarting the device.
I suspect the issue is related to the permission when SPDataPersistence tries to create the destination directory.
In that case it would be useful to avoid the directory creation and use an alternative solution (e.g.: UserDefaults)
In SPDataPersistence we use UserDefaults to store the session data when the platform is tvOS or watchOS, because on those the filesystem is not accessible as in iOS.
We can adopt the same solution when there are issues on iOS in order to avoid the crash.
> Fix SPDataPersistence crash at SDK init (close #655)

- Snowplow iOSTests/TestStateManager.m
- Snowplow/Internal/Tracker/SPStateManager.h
- Snowplow/Internal/Tracker/SPStateManager.m
- Snowplow/Internal/Tracker/SPTracker.m
Addresses issue #658 
The change automatically removes previous state machine (if any) with the same identifier when adding a new one. This prevents multiple of the same context being added to events in case the same state machine is registered multiple times.
> Do not allow multiple state machines with the same ID (close #658)

- Snowplow iOSTests/TestPlatformContext.m
- Snowplow iOSTests/Utils/SPMockDeviceInfoMonitor.h
- Snowplow iOSTests/Utils/SPMockDeviceInfoMonitor.m
- Snowplow/Internal/Subject/SPPlatformContext.m
Addresses issue #661 by updating the Apple IDFA and IDFV while they are `nil`. Once a value for them is found, they will no longer be updated.
> Fix updating IDFA during app runtime (close #661)

- Snowplow iOSTests/Configurations/TestTrackerConfiguration.m
- Snowplow iOSTests/TestSession.m
- Snowplow iOSTests/TestUtils.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/Configurations/SPSessionConfiguration.h
- Snowplow/Internal/Configurations/SPSessionConfiguration.m
- Snowplow/Internal/Session/SPSession.h
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Session/SPSessionConfigurationUpdate.h
- Snowplow/Internal/Session/SPSessionConfigurationUpdate.m
- Snowplow/Internal/Session/SPSessionControllerImpl.m
- Snowplow/Internal/Session/SPSessionState.h
- Snowplow/Internal/Session/SPSessionState.m
- Snowplow/Internal/Tracker/SPServiceProvider.m
- Snowplow/Internal/Utils/SPDataPersistence.m
- Snowplow/Snowplow-umbrella-header.h
- Snowplow/include/SPSessionState.h
- SnowplowTracker.podspec
The proposed session callback makes use of the SessionState which contains all the information normally available in the session context.
The current implementation is tailor-made on the specific problem of getting session information but in a further enhancement it could be generalised as callback that return information about any internal tracker state currently kept private (e.g: ScreenState, LifecycleState, etc.).
Little demo example here: https://github.com/snowplow-incubator/snowplow-objc-tracker-examples/pull/16
Proposed documentation:
--
Client session tracking is activated by default but it can be disabled through the TrackerConfiguration as explained above. When enabled the tracker appends a [client_session](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplo …
> Add session callback (close #664)

- Snowplow iOSTests/TestSession.m
- Snowplow/Internal/Session/SPSession.m
Not much to add to what is already described in the related issue (#667).
Suggested documentation:
---
Client session tracking is activated by default but it can be disabled through the TrackerConfiguration as explained above. When enabled the tracker appends a client_session context to each event it sends and it maintains this session information as long as the application is installed on the device.
Sessions correspond to tracked user activity. A session expires when no tracking events have occurred for the amount of time defined in a timeout (by default 30 minutes). The session timeout check is executed for each event tracked. If the gap between two consecutive events is longer than the timeout the session is renewed. There are two timeouts since a session can timeout in the foreground …
> Check session for background event using foreground timeout (close #667)

- Snowplow iOSTests/Configurations/TestEmitterConfiguration.m
- Snowplow iOSTests/Legacy Tests/LegacyTestEmitter.m
- Snowplow iOSTests/Utils/SPMockNetworkConnection.h
- Snowplow iOSTests/Utils/SPMockNetworkConnection.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/Emitter/SPEmitter.h
- Snowplow/Internal/Emitter/SPEmitter.m
- Snowplow/Internal/Emitter/SPEmitterConfigurationUpdate.h
- Snowplow/Internal/Emitter/SPEmitterController.h
- Snowplow/Internal/Emitter/SPEmitterControllerImpl.m
- Snowplow/Internal/Tracker/SPServiceProvider.m
- Snowplow/Internal/Tracker/SPTracker.m
- TestServiceProvider.m
* Renames `pause` and `resume` functions in `Emitter` to `pauseTimer` and `resumeTimer`
* Add a `pause` and `resume` function to `EmitterController` that calls `pauseEmit` and `resumeEmit` on `Emitter`
* Add a test for the pause functionality into a new `TestEmitterConfiguration` test case
> Add pause and resume to EmitterController (close #672)

- Snowplow iOSTests/TestSession.m
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Session/SPSessionState.m
The bug is due to a wrong migration of the userId.
The userId wasn't were expected causing a nil value that the SPSessionState wasn't able to manage because it expected a non-nil value.
The new implementation test the migration from the previous stored data and makes the SPSessionState creation more defensive handling better possible missing values.
This patch release is urgent and should be released ASAP.
We should also re-check the Android tracker, in case we spot anything like this.
> Fix object cannot be nil (key: userId) when initialising Snowplow tracker (close #675)

- Snowplow iOSTests/TestGeneratedJsons.m
- Snowplow iOSTests/TestSession.m
- Snowplow iOSTests/TestUtils.m
- Snowplow/Internal/SPTrackerConstants.h
- Snowplow/Internal/SPTrackerConstants.m
- Snowplow/Internal/Session/SPSession.h
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Session/SPSessionState.h
- Snowplow/Internal/Session/SPSessionState.m
- Snowplow/Internal/Tracker/SPTracker.m
- Snowplow/Internal/Utils/SPUtilities.h
- Snowplow/Internal/Utils/SPUtilities.m
This PR addresses issue #682 and updates the version of the `client_session` schema to 1-0-2. This adds two new entities:
* `eventIndex` which counts the order of the event in the session
* `firstEventTimestamp` which is the timestamp of the first event in the session
The changes are only internal within the session.
The only change in the documentation was to update the version of the schema. [Here is the PR for it](https://github.com/snowplow-incubator/data-value-resources/pull/111).
> Add eventIndex and firstEventTimestamp properties to client sessions (close #682)

- Snowplow iOSTests/Configurations/TestEmitterConfiguration.m
- Snowplow iOSTests/Legacy Tests/LegacyTestEmitter.m
- Snowplow iOSTests/TestRequest.m
- Snowplow iOSTests/TestRequestResult.m
- Snowplow iOSTests/Utils/SPMockNetworkConnection.h
- Snowplow iOSTests/Utils/SPMockNetworkConnection.m
- Snowplow/Internal/Configurations/SPEmitterConfiguration.h
- Snowplow/Internal/Configurations/SPEmitterConfiguration.m
- Snowplow/Internal/Emitter/SPEmitter.h
- Snowplow/Internal/Emitter/SPEmitter.m
- Snowplow/Internal/Emitter/SPEmitterConfigurationUpdate.h
- Snowplow/Internal/Emitter/SPEmitterConfigurationUpdate.m
- Snowplow/Internal/Emitter/SPRequestResult.h
- Snowplow/Internal/Emitter/SPRequestResult.m
- Snowplow/Internal/NetworkConnection/SPDefaultNetworkConnection.m
- Snowplow/Internal/Tracker/SPServiceProvider.m
- TestServiceProvider.m
This PR addresses issue #684.
It adds a set of 5 HTTP status codes (400, 401, 403, 410, and 422) for which sending events should not be retried and the events should be dropped. This is in line with the strategy for handling HTTP status codes that we [outlined here](https://github.com/snowplow-incubator/data-value-resources/blob/main/30%20Tracker%20Architecture/emitter_architecture/handling_http_status_codes.md).
It also makes the retry behaviour configurable. It adds the `customRetryForStatusCodes` property to `EmitterConfiguration`. This is a dictionary mapping status codes (int) to booleans stating whether to retry or not.
I added a note about the property in the documentation as well. [Here is a PR](https://github.com/snowplow-incubator/data-value-resources/pull/112) for it on …
> Add a customizable set of failure HTTP status codes for which collector requests should not be retried (close #684)

- Snowplow iOSTests/Configurations/TestRemoteConfiguration.m
- Snowplow/Internal/Configurations/SPRemoteConfiguration.h
- Snowplow/Internal/RemoteConfiguration/SPConfigurationCache.h
- Snowplow/Internal/RemoteConfiguration/SPConfigurationCache.m
- Snowplow/Internal/RemoteConfiguration/SPConfigurationProvider.m
Addresses issue #688 which goal was to support switching between remote configurations with different endpoints. This was not previously possible because the tracker cached previous configurations and didn't consider the endpoint when using the cache. Thus, if one switched to a new remote configuration with a new endpoint, a cache for the previous one could still be used by the tracker.
The approach that I chose is to add a hash of the remote config endpoint URL into the cache file name. So instead of `.../snowplow-cache/remoteConfig.data`, the cache files are now called `.../snowplow-cache/remoteConfig-12498219.data` where the number (12498219) is the hashcode of the URL. I make use of the NSString hash function which is not the most reliable hash but I think it's sufficient for this …
> Do not resume remote configuration from cache in case it has different endpoint (close #688)

- .github/workflows/build.yml
Github deprecated macos 10.15 for use in Github actions so I had to bump a few platform versions in the build. iOS 12.4 is also no longer available. I tried iOS 13 but there were issues with build using Carthage that I wasn't able to fix. Ended up with iOS 14.4 and added also 15.5 into the test builds.
| Previously | Now |
|---|---|
| {ios: 14.4, iphone: iPhone 11, watchos: 7.2, watch: Apple Watch Series 5 - 44mm, macos: '10.15', xcode: 12.4} | {ios: 15.5, iphone: iPhone 12 Pro, watchos: 8.5, watch: Apple Watch Series 5 - 44mm, macos: '12', xcode: 13.4} |
| {ios: 12.4, iphone: iPhone 5s, watchos: 5.3, watch: Apple Watch Series 2 - 38mm, macos: 10.15, xcode: 10.3} | {ios: 14.4, iphone: iPhone 8, watchos: 7.2, watch: Apple Watch Series 4 - 40mm, macos: '11', xcode: 12.4} |
> Upgrade deprecated macOS and XCode versions in Github actions (close #696)

- Snowplow iOSTests/Configurations/TestRemoteConfiguration.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/RemoteConfiguration/SPConfigurationFetcher.m
- Snowplow/Internal/RemoteConfiguration/SPConfigurationProvider.h
- Snowplow/Internal/RemoteConfiguration/SPConfigurationProvider.m
- Snowplow/Internal/RemoteConfiguration/SPConfigurationState.h
- Snowplow/Internal/SPSnowplow.h
- Snowplow/Internal/SPSnowplow.m
- Snowplow/include/SPConfigurationState.h
- SnowplowTracker.podspec
This PR addresses issue #694 and adds information about the remote configuration state to the `onSuccess` callback.
The configuration state describes where was the configuration retrieved from. It can have one of three values:
1. `CACHED` - retrieved from local cache file
2. `DEFAULT` - there was no cache, so the default settings provided by user were used
3. `FETCHED` - retrieved from the remote endpoint
This should make it more clear how to handle repeating calls to the `onSuccess` callback.
There are still some cases when we don't give any information to the user which makes it more difficult to get visibility of the remote config. However, these states don't really fit into the `onSuccess` callback so I decided to skip them here. But we could provide additional callbacks in the …
> Extend the onSuccess callback when setting up remote configuration to pass configuration state (close #694)

- Snowplow iOSTests/TestWebViewMessageHandler.m
- Snowplow iOSTests/Utils/SPMockNetworkConnection.m
- Snowplow iOSTests/Utils/SPMockWKScriptMessage.h
- Snowplow iOSTests/Utils/SPMockWKScriptMessage.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/SPSnowplow.h
- Snowplow/Internal/SPSnowplow.m
- Snowplow/Internal/Tracker/SPWebViewMessageHandler.h
- Snowplow/Internal/Tracker/SPWebViewMessageHandler.m
This PR addresses issue #691 and adds an option to subscribe to events tracked inside web view using the [WebView tracker](https://github.com/snowplow-incubator/snowplow-webview-tracker) ([WebView tracker PR here](https://github.com/snowplow-incubator/snowplow-webview-tracker/pull/3)).
The change is part of the hybrid app tracking solution – this PR enables the iOS tracker to listen for the forwarded events from the WebView tracker.
```mermaid
flowchart TB
subgraph hybridApp[Hybrid Mobile App]
subgraph webView[Web View]
webViewCode[App logic]
webViewTracker[Snowplow WebView tracker]
webViewCode -- "Tracks events" --> webViewTracker
end
subgraph nativeCode[Native Code]
nativeAppCode[App logic]
nativeTracker[Snowplow iOS/Android tracker]
nativeAppCode -- "Tracks events" --> nativeTracker …
```
> Add interface to subscribe for events tracked in Web views (close #691)

- Snowplow iOSTests/TestNetworkConnection.m
- Snowplow/Internal/NetworkConnection/SPDefaultNetworkConnection.m
Addresses issue #695 and adds simple logic to strip trailing slashes in collector endpoint URLs.
> Ignore trailing slashes in the network configuration endpoint (close #695)

- Snowplow/Internal/ScreenViewTracking/UIViewController+SPScreenView_SWIZZLE.m
This PR addresses issue #689.
The problem was that the screen view autotracking tracked too many events for non-relevant views (e.g., for the on-screen keyboard). I found a simple solution for it – just filter out views that are not in the main bundle.
Not sure if that condition is too strict. I don't expect users to have views in different bundles, but don't have much experience with UIKit, so correct me if I'm wrong.
> Fix too many events tracked by screen view autotracking (close #689)

- Snowplow iOSTests/TestGeneratedJsons.m
- Snowplow iOSTests/TestSession.m
- Snowplow/Internal/Session/SPSession.h
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Tracker/SPTracker.m
This is a tiny change that removes old timeout configuration in `SPSession` and `SPTracker` to avoid confusion. Issue #708 
* In `SPSession`, I removed the `init` constructor without any arguments – it wasn't used anywhere except for the tests and unnecessarily caused duplication of the default values (the Android tracker doesn't have one). Hopefully this is not a breaking change as the class is internal.
* In `SPTracker`, I updated the session foreground and background timeouts to the 30 minute default.
> Fix default session timeout values to 30 minutes everywhere (close #708)

- Snowplow iOSTests/Configurations/TestTrackerConfiguration.m
- Snowplow iOSTests/Legacy Tests/LegacyTestTracker.m
- Snowplow/Internal/Tracker/SPTracker.h
- Snowplow/Internal/Tracker/SPTracker.m
- Snowplow/Internal/Tracker/SPTrackerController.h
- Snowplow/Internal/Tracker/SPTrackerControllerImpl.m
Addresses issue #710 and makes the track method return the event ID as a `NSUUID *`. The change is quite small as the ID was already present in the method, it was only necessary to return it.
> Return tracked event ID from the track method (close #710)

- Snowplow/Internal/Tracker/SPTracker.h
- Snowplow/Internal/Tracker/SPTrackerController.h
Addresses issue https://github.com/snowplow/snowplow-objc-tracker/issues/713 By making the UUID returned by the track function nullable, which was previously assumed to be non-null by `NS_ASSUME_NONNULL`. This will prevent crashes when calling track after event tracking has been paused.
> Add nullable modifier to prevent crashes in track function (close #713)

- Snowplow iOSTests/Utils/SPMockLoggerDelegate.h
- Snowplow iOSTests/Utils/SPMockLoggerDelegate.m
- Snowplow.xcodeproj/project.pbxproj
- Snowplow/Internal/Emitter/SPEmitter.m
- Snowplow/Internal/Tracker/SPServiceProvider.m
- Snowplow/Internal/Tracker/SPServiceProviderProtocol.h
- Snowplow/Internal/Tracker/SPTrackerControllerImpl.m
- TestServiceProvider.m
Issue #716 
The problem that we are dealing with here is that users got confusing behaviour after having code that did something similar to this:
```swift
let tracker = Snowplow.createTracker(...);
Snowplow.removeTracker(tracker);
print("Tracker removed: " + tracker.namespace);
```
In this case the tracker was removed on the second line but it was reinitialized on the third line, which is not obvious based on the snippet. Reinitializing the tracker also means that various autotracking features may be reactivated and unexpected events tracked.
I would like to prevent this behaviour and just return NULL from the `getNamespace()` and other functions from the `TrackerController` but I realized that this would be a breaking change. We would need to change the signature of the …
> Log an error when recreating tracker after being removed (close #716)

- Snowplow/Internal/Emitter/SPEmitterControllerImpl.m
Issue #722 
Add missing `@synthesize` directive for the `customRetryForStatusCodes` property in `SPEmitterControllerImpl`.
> Fix compiler warning in SPEmitterControllerImpl to synthesize customRetryForStatusCodes (close #722)

- Snowplow iOSTests/TestEvents.m
- Snowplow/Internal/Tracker/SPTracker.m
Issue #718  
This PR extends the workaround in the tracker which sets the page referrer and page URL atomic properties in events – previously it only set them for deep link events based on their properties. Now, it also sets them for screen view events based on the deep link context entities.
I had to move the workaround to a different place. Previously it was called in `addSelfDescribingPropertiesToPayload()` in Tracker but at that point the events do not contain context entities assigned using state machines. Since the deep link entity is added in a state machine, I moved the call to after state machine context entities are added to events.
> Add DeepLink entity referrer and url to atomic properties in ScreenView events (close #718)

- Snowplow iOSTests/Configurations/TestTrackerController.m
- Snowplow iOSTests/Legacy Tests/LegacyTestSubject.m
- Snowplow iOSTests/TestSession.m
- Snowplow iOSTests/TestSubject.m
- Snowplow/Internal/Configurations/SPTrackerConfiguration.h
- Snowplow/Internal/Session/SPSession.m
- Snowplow/Internal/Subject/SPSubject.h
- Snowplow/Internal/Subject/SPSubject.m
- Snowplow/Internal/Tracker/SPTracker.h
- Snowplow/Internal/Tracker/SPTracker.m
Issue #720 
Anonymises additional properties when `TrackerConfiguration.userAnonymisation` is enabled. In particular, the following additional properties are anonymised:
* Session context entity
* `previousSessionId` – otherwise one could recreate the whole user journey from the chain of sessions and basically recreate a user id
* Subject
* `userId` – also anonymised in the JavaScript tracker
* `domainUserId` – also anonymised in the JavaScript tracker
* `networkUserId` – anonymised when server anonymisation is enabled, I think it makes sense to also anonymise if it is set client-side
* `ipAddress` – anonymised when server anonymisation is enabled, I think it makes sense to also anonymise if it is set client-side
Anonymous tracking is a tracker feature that enables anonymising various …
> Anonymise previous session ID and user identifiers in subject when user anonymisation is enabled (close #720)

- .github/workflows/build.yml
- .slather.yml
- Sources/Core/Tracker/StateFuture.swift
- Sources/Core/Tracker/StateManager.swift
- Sources/Core/Tracker/TrackerState.swift
- Sources/Snowplow/Events/SelfDescribing.swift
- Tests/Configurations/TestRemoteConfiguration.swift
- Tests/Integration/TestTrackEventsToMicro.swift
- Tests/TestNetworkConnection.swift
- Tests/Utils/Micro.swift
Issue #736 
This PR adds integration tests using Micro. After removing event payload schema validation using Iglu Client in the previous PR, Micro will enable us to validate event payloads against their schemas.
The main goal here is to set up the helpers and CI so that it is easy to write Micro tests. I implemented just a few tests, they don't cover all the main use cases yet, but they focus on some more scenarios that involve tracking multiple events (such as adding the previous screen view references or deep link information).
The helpers are in the `Micro` class which makes requests to Micro and also retries for a number of times to account for delays in updating Micro (the nice thing is that the actual tests don't need to worry about that and so are easier to read).
> Add tests using Micro for payload validation (close #736)

- Sources/Core/Utils/Utilities.swift
- Sources/Snowplow/Configurations/Configuration.swift
- Sources/Snowplow/Configurations/NetworkConfiguration.swift
- Sources/Snowplow/Configurations/SessionConfiguration.swift
- Sources/Snowplow/Configurations/SubjectConfiguration.swift
- Sources/Snowplow/Configurations/TrackerConfiguration.swift
- Sources/Snowplow/Emitter/EventStore.swift
- Sources/Snowplow/Entities/DeepLinkEntity.swift
- Sources/Snowplow/Entities/LifecycleEntity.swift
- Sources/Snowplow/Events/Background.swift
- Sources/Snowplow/Events/ConsentDocument.swift
- Sources/Snowplow/Events/ConsentGranted.swift
- Sources/Snowplow/Events/ConsentWithdrawn.swift
- Sources/Snowplow/Events/DeepLinkReceived.swift
- Sources/Snowplow/Events/Ecommerce.swift
- Sources/Snowplow/Events/EcommerceItem.swift
- Sources/Snowplow/Events/EventBase.swift
- Sources/Snowplow/Events/Foreground.swift
- Sources/Snowplow/Events/MessageNotification.swift
- Sources/Snowplow/Events/MessageNotificationAttachment.swift
- Sources/Snowplow/Events/PageView.swift
- Sources/Snowplow/Events/PushNotification.swift
- Sources/Snowplow/Events/SNOWError.swift
- Sources/Snowplow/Events/ScreenView.swift
- Sources/Snowplow/Events/SelfDescribing.swift
- Sources/Snowplow/Events/Structured.swift
- Sources/Snowplow/Events/Timing.swift
- Sources/Snowplow/Events/TrackerError.swift
- Sources/Snowplow/Snowplow.swift
- Sources/Snowplow/Tracker/InspectableEvent.swift
Issue #740 
* Update API comments for the Swift-DocC format.
* Add missing comments for several classes where they were missing.
* Remove `public` from methods and properties that should not be published.
API docs deployed here: http://snowplow.github.io/snowplow-objc-tracker/documentation/snowplowtracker/snowplow/
> Update API comments for Swift-DocC and add missing comments (close #740)

- Sources/Core/Subject/PlatformContext.swift
- Sources/Core/Subject/Subject.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Core/Tracker/Tracker.swift
- Sources/Core/Tracker/TrackerConfigurationUpdate.swift
- Sources/Core/Tracker/TrackerControllerImpl.swift
- Sources/Core/Utils/DeviceInfoMonitor.swift
- Sources/Snowplow/Configurations/TrackerConfiguration.swift
- Tests/Legacy Tests/LegacyTestSubject.swift
- Tests/TestPlatformContext.swift
- Tests/TestSubject.swift
- Tests/Utils/MockDeviceInfoMonitor.swift
Issue #678 
This PR deals addresses the issue present in both v4 and v5 versions of the tracker where it is not possible to enable the IDFA identifier in platform context when using Swift Package Manager. Previously it was enabled by a preprocessor macro which is currently not possible to add through SPM.
There was a suggestion in the issue to solve this by adding a secondary target and library in the SPM package – something like `SnowplowTrackerWithIDFA`. So one would choose whether to include or not the IDFA by using a different library. This might work but is a bit unintuitive to have a completely separate package just because of the configuration. Also when I tried it, I ran into an issue that SPM does not support having multiple targets using the same source code.
I decided to …
> Add a closure to tracker configuration that enables retrieving IDFA value and replaces the use of SNOWPLOW_IDFA_ENABLED macro (close #678)

- Sources/Core/GlobalContexts/GlobalContextPluginConfiguration.swift
- Sources/Core/GlobalContexts/GlobalContextsControllerImpl.swift
- Sources/Core/ScreenViewTracking/ScreenStateMachine.swift
- Sources/Core/StateMachine/DeepLinkStateMachine.swift
- Sources/Core/StateMachine/LifecycleStateMachine.swift
- Sources/Core/StateMachine/PluginStateMachine.swift
- Sources/Core/StateMachine/StateMachineProtocol.swift
- Sources/Core/StateMachine/StateManager.swift
- Sources/Core/Tracker/PluginsControllerImpl.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Core/Tracker/ServiceProviderProtocol.swift
- Sources/Core/Tracker/Tracker.swift
- Sources/Core/Tracker/TrackerControllerImpl.swift
- Sources/Core/Tracker/TrackerEvent.swift
- Sources/Snowplow/Configurations/GlobalContextsConfiguration.swift
- Sources/Snowplow/Configurations/PluginConfiguration.swift
- Sources/Snowplow/Controllers/PluginsController.swift
- Sources/Snowplow/Controllers/TrackerController.swift
- Tests/Global Contexts/TestGlobalContexts.swift
- Tests/Integration/TestTrackEventsToMicro.swift
- Tests/TestPlugins.swift
- Tests/TestScreenViewModifier.swift
- Tests/TestServiceProvider.swift
- Tests/TestStateManager.swift
Issue #750 
Implements the ability to provide custom plugins that can intercept tracked events. Plugins provide callbacks that can enrich events with additional entities and inspect tracked events.
**Code snippet**
The API is explained in this snippet:
```swift
// identifier needs uniquely identify the plugin
let plugin = PluginConfiguration(identifier: "myPlugin")
// entities closure can return context entities to enrich events
// the list of schemas to call the closure for is optional (it will be called for all events if null)
plugin.entities(schemas: ["iglu:..."]) { event in
return [
SelfDescribingJson(schema: "iglu:xx", andData: ["yy": true])
]
}
// after track callback called on a background thread to inspect final tracked events
// one can also supply a list of schemas to call the …
```
> Add ability to provide custom tracker plugins to inspect and enrich tracked events (close #750)

- Sources/Core/GDPR/GDPRConfigurationUpdate.swift
- Sources/Core/GlobalContexts/GlobalContextPluginConfiguration.swift
- Sources/Core/RemoteConfiguration/FetchedConfigurationBundle.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Snowplow/Configurations/ConfigurationBundle.swift
- Sources/Snowplow/Configurations/ConfigurationProtocol.swift
- Sources/Snowplow/Configurations/EmitterConfiguration.swift
- Sources/Snowplow/Configurations/FocalMeterConfiguration.swift
- Sources/Snowplow/Configurations/GDPRConfiguration.swift
- Sources/Snowplow/Configurations/GlobalContextsConfiguration.swift
- Sources/Snowplow/Configurations/NetworkConfiguration.swift
- Sources/Snowplow/Configurations/PluginConfiguration.swift
- Sources/Snowplow/Configurations/RemoteConfiguration.swift
- Sources/Snowplow/Configurations/SerializableConfiguration.swift
- Sources/Snowplow/Configurations/SessionConfiguration.swift
- Sources/Snowplow/Configurations/SubjectConfiguration.swift
- Sources/Snowplow/Configurations/TrackerConfiguration.swift
- Sources/Snowplow/Snowplow.swift
- Tests/TestPlugins.swift
Issue #752 
Currently the `Configuration` class implements `NSCopying` and `NSSecureCoding` which makes it possible to serialize configuration objects which is useful for remote configuration.
However, not all configurations are used in remote configuration and some are not event possible to implement that way (e.g., global contexts, plugins). It is unnecessary to require all configurations to implement the serialization and makes it more difficult to create new plugins.
This PR removes the `NSCopying` and `NSSecureCoding` implementation from `Configuration` and moves it to `SerializableConfiguration` which is implemented only where relevant. Also the `Configuration` class can now be a protocol, so I renamed it to `ConfigurationProtocol`.
> Remove requirement for all configurations to be serializable (close #752)

- .gitmodules
- CONTRIBUTING.md
- README.md
- SnowplowTracker.podspec
Rename references to the Github repository from `snowplow-objc-tracker` to `snowplow-ios-tracker`.
> Rename the repository from snowplow-objc-tracker to snowplow-ios-tracker

- Sources/Snowplow/Configurations/FocalMeterConfiguration.swift
- Tests/Configurations/TestFocalMeterConfiguration.swift
Issue #745 
Similar to PR #746 which implemented the FocalMeter configuration for the version 4, this PR implements the configuration for version 5 of the tracker. In contrast with the v4 implementation, this one makes use of the new plugin API and the `afterTrack` callback. The public API is the same as for v4.
The tracker has the ability to send the user identifier (`userId` present in the session context) to a [Kantar FocalMeter](https://www.virtualmeter.co.uk/focalmeter) endpoint. This integration enables measuring the audience of content through the FocalMeter router meter.
To enable this feature, you can pass the `FocalMeterConfiguration` configuration with the URL of the Kantar endpoint. For example:
```swift
let focalMeterConfig = FocalMeterConfiguration(kantarEndpoint: …
```
> Add configuration to send requests with user ID to a Focal Meter endpoint (close #745)

- .github/workflows/build.yml
- Sources/Core/Session/Session.swift
- Tests/TestSession.swift
Issue #767 
Fixes a bug introduced in v5 of the tracker where the `previousSessionId` was not tracked in the `client_session` context entity in case anonymous tracking was enabled. This caused validation errors.
The fix is by setting the property to `NSNull` which ensures that it will be serialized as null in the JSON.
> Fix validation errors due to session schema tracked without required previousSessionId property when anonymous tracking (close #767)

- Sources/Core/RemoteConfiguration/ConfigurationCache.swift
A bug was reported when using certain remote config URIs. If the URI hash was negative, the tracker crashed with "Fatal error: Negative value is not representable" due to the negative number being passed to `UInt`.
> Fix remote config negative hash bug

- Sources/Core/Session/Session.swift
Issue #776 
The memory leak was in the `Session` class which holds a reference to the tracker. Since the reference was strong, the tracker was kept in memory even in case it was no longer referenced in `ServiceProvider`.
I changed it to a weak reference which means that the lifetime of the tracker object is no longer determined by that reference.
> Fix memory leak when tracker is created using remote configuration (close #776)

- Sources/Core/Emitter/Emitter.swift
Addresses issue #774 that reported a problem with concurrent access to the `isSending` property in Emitter which wasn't thread-safe.
To address the problem, this PR creates a wrapper class `SendingLock` around the `isSending` property that protects access to the value using a lock.
> Handle unprotected access to sending state in Emitter from concurrent threads (close #774)

- Sources/Core/GlobalContexts/GlobalContextPluginConfiguration.swift
- Sources/Core/ScreenViewTracking/ScreenStateMachine.swift
- Sources/Core/StateMachine/DeepLinkStateMachine.swift
- Sources/Core/StateMachine/LifecycleStateMachine.swift
- Sources/Core/StateMachine/PluginStateMachine.swift
- Sources/Core/StateMachine/StateMachineProtocol.swift
- Sources/Core/StateMachine/StateManager.swift
- Sources/Core/Tracker/PluginsControllerImpl.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Core/Tracker/ServiceProviderProtocol.swift
- Sources/Core/Tracker/Tracker.swift
- Sources/Snowplow/Configurations/PluginConfiguration.swift
- Sources/Snowplow/Controllers/PluginsController.swift
- Tests/Legacy Tests/LegacyTestTracker.swift
- Tests/TestPlugins.swift
- Tests/TestStateManager.swift
Issue #783 
Adds a new `filter` callback to plugins which enables deciding whether to track an event or not. This can be useful for filtering auto-tracked events by the tracker.
For instance, this snippet filters screen view events to keep only ones with a specific name property:
```swift
plugin.filter(schemas: [
"iglu:com.snowplowanalytics.snowplow/screen_view/jsonschema/1-0-0", // screen view events
]) { event in
return event.payload["name"] as? String == "Home Screen"
}
```
[Here is a commit adding the documentation for the filter function](https://github.com/snowplow/documentation/commit/79410621b205fdbbcc2ef3dd20264121e15a8238).
> Add a filter API to plugins to decide whether to track an event or not (close #783)

- Sources/Core/Storage/SQLiteEventStore.swift
- Tests/Configurations/TestEmitterConfiguration.swift
Issue #789 
The `emitRange` Emitter configuration has been ignored in the `SQLiteEventStore` (it's a long standing bug). Instead, the event store only followed an internal setting for the send limit.
This PR fixes the issue by using the minimum of the Emitter `emitRange` and the event store `sendLimit` configuration when choosing how many events to emit from the store.
> Fix emit range configuration in Emitter not respected if using SQLite event store (close #789)

- Sources/Core/Tracker/Tracker.swift
- Sources/Core/Utils/Utilities.swift
- Tests/TestEvents.swift
- Tests/TestUtils.swift
Issue #793
This PR addresses the issue that the URL scheme may be quite long for deep links but the atomic events schema limits the max length of the scheme to 16 characters for page_url and page_refr properties, [see here](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0#L136). This can lead to validation errors when deep links with longer URL schemes are tracked.
To solve the issue, the tracker now truncates the URL scheme in page_url and page_refr properties to 16 chars. This only affects the values in the atomic properties, the URLs in the deep link event and context entity are not truncated.
> Truncate URL scheme for page_url and page_refr properties (close #793)

- Sources/Snowplow/Configurations/ConfigurationBundle.swift
- Sources/Snowplow/Configurations/EmitterConfiguration.swift
- Sources/Snowplow/Emitter/BufferOption.swift
- Tests/Configurations/TestRemoteConfiguration.swift
Issue #782
This PR adds support for loading the emitter configuration in remote configuration. The following properties of emitter configuration can be loaded:
* bufferOption
* emitRange
* threadPoolSize
* byteLimitGet
* byteLimitPost
* customRetryForStatusCodes
* serverAnonymisation
Other ones such as the event store and request callback can not be serialized in remote configuration but can be supplied through default configuration.
> Add emitter configuration support to remote configuration (close #782)

- Sources/Core/Subject/PlatformContext.swift
- Tests/TestPlatformContext.swift
- Tests/Utils/MockDeviceInfoMonitor.swift
Issue #795
This PR handles situations where the language property in the `mobile_context` entity was longer than 8 characters, which caused validation errors as the property has a `maxLength` setting of 8 chars.
> Truncate language in platform context entity to max 8 characters (close #795)

- Sources/Core/Tracker/TrackerControllerImpl.swift
- Sources/Core/Utils/Stringb64.swift
- Sources/Snowplow/Controllers/TrackerController.swift
- Sources/Snowplow/Tracker/CrossDeviceParameterConfiguration.swift
- Sources/Snowplow/Tracker/DevicePlatform.swift
- Tests/TestLinkDecorator.swift
This PR adds a method to the tracker to decorates a URL, provided by the user, with session/user info for cross-device/platform tracking.
> Add API to decorate link with user/session info

- .github/workflows/build.yml
- Integrationtests/TestTrackEventsToMicro.swift
- Integrationtests/Utils/Micro.swift
- Package.swift
This PR aims to improve the flakiness of the integration tests in the following ways:
* Separate out a new testing target for the integration tests and only run it on iOS. It is not necessary to run the integration tests on all platforms and this makes the impact of flaky tests smaller.
* The integration tests are run separately from unit tests. Even in case they fail, it will be contained to that one test run and less tests have to be re-run.
* Don't use the fail-fast strategy on the tests in CI because that cancels any other jobs in case one of them fails. It makes the impact of flaky tests larger.
While these changes don't solve the flakiness, I think they can significantly improve the impact of the flakiness of the tests so that it happens less often and is faster to re-run failed …
> Separate test targets for unit and integration tests

- Sources/Core/Tracker/Tracker.swift
- Sources/Core/Tracker/TrackerEvent.swift
- Sources/Core/Utils/DispatchQueueWrapper.swift
- Sources/Core/Utils/DispatchQueueWrapperProtocol.swift
- Tests/Configurations/TestTrackerConfiguration.swift
- Tests/Configurations/TestTrackerController.swift
- Tests/TestSession.swift
- Tests/Utils/MockDispatchQueueWrapper.swift
Tracked events - `Tracker.track(event)` - are processed into Payloads and stored in memory (`Emitter.addPayload()`). This currently occurs on the main thread, which could cause performance issues.
This change adds a new serial async queue to the Tracker. There is a small change in the meaning of the return value from `Tracker.track(event)`. This method returns `UUID?`: currently, `nil` can be returned either if the tracker is paused, or if the event ended up getting filtered out by a plugin and not tracked. Now, `nil` will only mean that the tracker is paused.
> Process tracked events on a serial background queue (close #822)

- Package.resolved
- Package.swift
- SnowplowTracker.podspec
- Sources/Core/Storage/Database.swift
- Sources/Core/Storage/SQLiteEventStore.swift
- Tests/Storage/TestDatabase.swift
- Tests/Storage/TestSQLiteEventStore.swift
- Tests/Utils/DatabaseHelpers.swift
Issue #823 
This PR removes the FMDB dependency in favor of accessing the database directly using the `sqlite3` calls. The calls are wrapped in a `Database` class. Every call uses a new database connection.
The `SQLiteEventStore` class wraps the `Database` class and handles concurrency using a serial dispatch queue. All the calls in the `SQLiteEventStore` are synchronous as before.
> Remove the use of the FMDB dependency in SQLiteEventStore (close #823)

- .github/workflows/build.yml
- Sources/Core/RemoteConfiguration/RemoteConfigurationCache.swift
Simplifies the github build action so that it doesn't specify the OS versions – only the XCode version is specified for the unit and integration tests.
Also updates the lint action to use the latest XCode version.
Finally, use of a deprecated API (`NSKeyedUnarchiver.unarchiveTopLevelObjectWithData`) is replaced with the recommended one to avoid build failures.
> Update CI build

- Sources/Core/ScreenViewTracking/UIKitScreenViewTracking.swift
This PR addresses issue [#858](https://github.com/snowplow/snowplow-ios-tracker/issues/858) concerning the Snowplow SDK's bundle path handling in modularized iOS apps. The current `UIViewController` extension's method for tracking screen views fails on real iOS devices due to not accounting for the symbolic link between `/private/var/` and `/var/`.
The fix involves updating `sp_viewDidAppear` to use `resolvingSymlinksInPath()`, ensuring the bundle paths for both the main app and its frameworks are standardized. This method resolves `/private/var/` to `/var/`, aligning framework paths with the main app bundle. This change guarantees accurate tracking of view controllers across all frameworks on iOS devices.
> Fix bundle path check to handle symbolic links (close #858)

- Sources/Core/Emitter/Emitter.swift
- Sources/Core/Emitter/EmitterControllerImpl.swift
- Sources/Core/InternalQueue/EmitterControllerIQWrapper.swift
- Sources/Core/Storage/Database.swift
- Sources/Core/Storage/MemoryEventStore.swift
- Sources/Core/Storage/SQLiteEventStore.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Snowplow/Configurations/EmitterConfiguration.swift
- Sources/Snowplow/Emitter/EmitterDefaults.swift
- Sources/Snowplow/Emitter/EventStore.swift
- Tests/Storage/TestDatabase.swift
- Tests/TestMemoryEventStore.swift
- Tests/Utils/MockEventStore.swift
Issue #860 
The event store is currently unbounded meaning that if events fail to be sent to the collector, they are never removed from the event store. This can lead to it growing endlessly (if for instance an ad blocker blocks the collector domain) which is likely to have an impact on the app.
We should add configurable limits to the event store so that old events are removed. We could have two such limits:
* maximum event store size – in case the number of events surpasses this threshold, oldest events will be removed until we are under the threshold. Default could be 1000.
* maximum event age – in case there are events older than this threshold, we should remove them. Default could be 30 days.
The implementation in this PR adds these limits and enforces them before each emit attempt. …
> Add configurable limit for the maximum age and number of events in the event store and remove old events before sending (close #860)

- Sources/Snowplow/Events/EventBase.swift
- Tests/TestEvents.swift
Breaking changes in the `BaseEvent` class, to standardise the API with the Android tracker.
The `BaseEvent.entities()` builder method now appends the new list of entities, rather than replacing it.
> Match BaseEvent entities API with Android tracker

- Sources/Core/Emitter/Emitter.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Snowplow/Configurations/NetworkConfiguration.swift
- Sources/Snowplow/Emitter/EmitterDefaults.swift
- Sources/Snowplow/Network/DefaultNetworkConnection.swift
- Tests/TestNetworkConnection.swift
Issue #836 
This PR builds on top of PR #837 to add timeout to `DefaultNetworkConnection` while considering the open comments.
Additionally, this PR adds the `timeout` configuration to the `NetworkConfiguration` similar as it is on our Android tracker. It also sets the default timeout to 30 seconds to match the Android tracker setting.
> Add request timeout to network connection and configuration (close #836)

- Sources/Core/Tracker/TrackerDefaults.swift
- Sources/Snowplow/Configurations/TrackerConfiguration.swift
Issue #852
Up to the v5 version of the tracker, lifecycle autotracking is not enabled by default. However, lifecycle events are crucial to understand the usage of the app and user engagement. It is not possible to calculate screen time without knowing whether the app is in foreground or background.
As we are introducing screen engagement tracking in the v6 version which will be enabled by default, we should also enable lifecycle tracking by default.
> Enable lifecycle autotracking by default (close #852)

- Sources/Core/Emitter/EmitterControllerImpl.swift
- Sources/Core/InternalQueue/EmitterControllerIQWrapper.swift
- Sources/Core/InternalQueue/EventStoreIQWrapper.swift
- Sources/Snowplow/Controllers/EmitterController.swift
- Tests/Configurations/TestEmitterConfiguration.swift
Issue #834
This PR builds on top of PR #835 to wrap the exposed event store so that all calls are executed on the internal queue.
> Expose event store from emitter controller to be able to remove all events from database (close #834)

- Sources/Core/Utils/Utilities.swift
- Tests/TestUtils.swift
Previously, the `desktop` platform was used for watchOS and tvOS.
This PR changes the platform to `tv` on tvOS and `mob` on watchOS (don't have a wearable platform yet).
> Set the platform event property to tv on tvOS and mobile on watchOS

- Sources/Core/Media/Controllers/MediaTrackingImpl.swift
- Sources/Core/Media/Events/MediaPercentProgressEvent.swift
- Tests/Media/TestMediaController.swift
Issue #864 .
Adds the percentage progress to the percent progress event.
> Add percent progress to event

- Package@swift-5.9.swift
Remove warning when building project with swift 5.9
> Remove deprecated name property in SPM package file for the Mocker dependency on Swift 5.9

- Sources/Core/Tracker/Tracker.swift
Issue #889 
Conditionally performs UIKit swizzling in order to set up screen view autotracking.
Previously swizzling was done even if autotracking was disabled, this was not necessary and could cause problems in some apps.
This is PR adds a condition to not perform swizzling if autotracking is disabled.
> Do not swizzle views if screen view autotracking is disabled (close #889)

- SnowplowTracker.podspec
Issue #888 
The privacy info file was previously not exposed from the package when used through CocoaPods. This PR adds it to the resources for CocoaPods so that it is included.
> Add the PrivacyInfo to the CocoaPods podspec (close #888)

- Sources/Snowplow/Tracker/CrossDeviceParameterConfiguration.swift
When trying to decorate a link with extended parameters, this error presents itself: `'CrossDeviceParameterConfiguration' initializer is inaccessible due to 'internal' protection level`.
```swift
tracker.decorateLink(
URL(string: "https://test.com/")!,
extendedParameters: CrossDeviceParameterConfiguration(
sessionId: true,
subjectUserId: true,
sourceId: true,
sourcePlatform: true,
reason: "this is a reason"
)
)
```
From [the examples](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/session-tracking/#decorating-outgoing-links-using-cross-navigation-tracking), it looks like the initializer is meant to be public.
This PR simply adds `public` to the `init` method of the `CrossDeviceParameterConfiguration` class.
> Make CrossDeviceParameterConfiguration init public

- Sources/Snowplow/Events/SelfDescribing.swift
- Sources/Snowplow/Payload/SelfDescribingJson.swift
This PR adds a warning to `SelfDescribingJSON` and `SelfDescribing` classes to warn that the data needs to be serializable to JSON, otherwise an error will be thrown.
> Add warning for the serialization of data in self-describing event and entity

- Sources/Core/Tracker/WebViewMessageHandler.swift
- Tests/TestWebViewMessageHandler.swift
This fixes the problem when in case the WebView tracker tracked event or context data that included NaN values, the tracker and the app would crash.
In order to handle this case, this PR adds a a check for `JSONSerialization.isValidJSONObject` on both the event and context entities. In case either is not serializable, an error is logged and the event is skipped.
> Handle nan values and other non-serializable data in events from the WebView tracker

- Package.resolved
- Sources/Core/Events/WebViewReader.swift
- Sources/Core/Tracker/TrackerEvent.swift
- Sources/Core/Tracker/WebViewMessageHandlerV2.swift
- Sources/Core/TrackerConstants.swift
- Sources/Snowplow/Snowplow.swift
- Tests/TestWebViewMessageHandlerV2.swift
This PR is part of our upgrade to the Snowplow WebView tracker. It allows the tracking of all web events, including certain base/primitive event properties.
> Add new WebView Interface

- Sources/Core/InternalQueue/SessionControllerIQWrapper.swift
- Sources/Core/Session/Session.swift
- Sources/Core/Session/SessionControllerImpl.swift
- Sources/Core/Tracker/ServiceProvider.swift
- Sources/Core/Tracker/Tracker.swift
- Sources/Core/Tracker/TrackerDefaults.swift
- Sources/Core/TrackerConstants.swift
- Sources/Snowplow/Configurations/SessionConfiguration.swift
- Sources/Snowplow/Tracker/SessionState.swift
- Tests/Configurations/TestTrackerConfiguration.swift
- Tests/TestSession.swift
Adds an option to continue the previously persisted session when the app restarts.
The default behaviour is to always start a new session when a new tracker is created (i.e., when the app restarts) regardless of whether the previous one timed out or not.
With the option enabled, every session update is persisted to the UserDefaults storage. This includes the current event index in the session and a timestamp of the last update of the session. In case it's disabled, only session changes are persisted to UserDefaults.
The option can be configured using `SessionConfiguration`:
```swift
let sessionConfig = SessionConfiguration()
.continueSessionOnRestart(true)
```
> Add an option to continue previously persisted session when the app restarts rather than starting a new one
